//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonVu.Json.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonVu.Json.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hex number is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowHexNumber {
            get {
                return ResourceManager.GetString("DisallowHexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infinity is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowInfinity {
            get {
                return ResourceManager.GetString("DisallowInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last comma is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowLastComma {
            get {
                return ResourceManager.GetString("DisallowLastComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left zero padding number is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowLeftZeroPaddingNumber {
            get {
                return ResourceManager.GetString("DisallowLeftZeroPaddingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NaN is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowNaN {
            get {
                return ResourceManager.GetString("DisallowNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Non string key is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowNonStringKey {
            get {
                return ResourceManager.GetString("DisallowNonStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Octal number is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowOctalNumber {
            get {
                return ResourceManager.GetString("DisallowOctalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String in single quotation marks are not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowSingleQuoteString {
            get {
                return ResourceManager.GetString("DisallowSingleQuoteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   undefined is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowUndefined {
            get {
                return ResourceManager.GetString("DisallowUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown type is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisallowUnknownType {
            get {
                return ResourceManager.GetString("DisallowUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Array has not been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorArrayNotCompleted {
            get {
                return ResourceManager.GetString("ErrorArrayNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An incorrect value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorIncorrectValue {
            get {
                return ResourceManager.GetString("ErrorIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid character. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidCharacter {
            get {
                return ResourceManager.GetString("ErrorInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid object key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidObjectKey {
            get {
                return ResourceManager.GetString("ErrorInvalidObjectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An incorrect string value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNotCompletedStringValue {
            get {
                return ResourceManager.GetString("ErrorNotCompletedStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object Key has not been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNotSetObjectKey {
            get {
                return ResourceManager.GetString("ErrorNotSetObjectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object value has not been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNotSetObjectValue {
            get {
                return ResourceManager.GetString("ErrorNotSetObjectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object has not been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorObjectNotCompleted {
            get {
                return ResourceManager.GetString("ErrorObjectNotCompleted", resourceCulture);
            }
        }
    }
}
