//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonVu.Json.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonVu.Json.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   An incorrect value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorIncorrectValue {
            get {
                return ResourceManager.GetString("ErrorIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid character に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidCharacter {
            get {
                return ResourceManager.GetString("ErrorInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid object key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidObjectKey {
            get {
                return ResourceManager.GetString("ErrorInvalidObjectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property key has not been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNotSetPropertyKey {
            get {
                return ResourceManager.GetString("ErrorNotSetPropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property value has not been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorNotSetPropertyValue {
            get {
                return ResourceManager.GetString("ErrorNotSetPropertyValue", resourceCulture);
            }
        }
    }
}
